create type vehicle_type_enum as enum ('car', 'truck', 'bus', 'bike');

alter type vehicle_type_enum owner to postgres;

create table visit_statistics
(
    statistic_id serial
        primary key,
    visit_date   date         not null,
    vehicle_type varchar(255) not null,
    count        bigint default 0,
    id           bigint generated by default as identity,
    unique (visit_date, vehicle_type)
);

alter table visit_statistics
    owner to postgres;

create table users
(
    phone_number varchar(255) not null,
    name         varchar(255) not null,
    email        varchar(255) not null
        constraint unique_email
            unique,
    password     varchar(255) not null,
    role         varchar(255) not null,
    user_name    varchar(255) not null
        constraint unique_user_name
            unique,
    id           bigint generated by default as identity,
    created_at   timestamp(6),
    updated_at   timestamp(6)
);

alter table users
    owner to postgres;

